name: Deploy Docker Hello World with SonarQube

on:
  push:
    branches:
      - main  # Runs on every push to main branch

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world:latest .

      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hello-world:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-scan
    steps:
    # Step 5: Docker Login on EC2
    - name: SSH into EC2 and Deploy to Kubernetes
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_INSTANCE_IP }}
        username: ec2-user
        password: ${{ secrets.EC2_PASSWORD }}
        port: 22
        script: |
          # Docker Login
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          # Pull Docker Image
          docker pull ${{ secrets.DOCKER_USERNAME }}/hello-world:latest 
          docker run -d -p 8081:80 ${{ secrets.DOCKER_USERNAME }}/hello-world:latest
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
            
            # Verify Deployment
            kubectl get pods
            kubectl get svc
          
